version: "3"
services:
    apthailand:
        container_name: kingpower
        build:
            context: .
            dockerfile: kingpower/Dockerfile
        volumes:
            - /app/node_modules
        ports:
            - "3000:3000"
        restart: always
 
    mongodb:
        container_name: mongodb
        image: mongo
        ports:
          - "27017:27017"
        restart: always
        
    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - "8081:8081"
        restart: always